name: "Google Assitant Broadcast"
description: "Takes requests to make broadcasts on your home network"
version: "1.0.0"
slug: "google-assistant-broadcast"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
